### ISSUE TITLE
java.lang.SecurityException: PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission

### ISSUE THREAD

**Issue by BorntraegerMarc** [WebsiteBeaver/CordovaCall#56]
When using this plugin for android phones I get the following error after a production build:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.komedhealth.frontend, PID: 6191
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.komedhealth.frontend/com.komedhealth.frontend.MainActivity}: java.lang.SecurityException: PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.SecurityException: PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission.
                      at android.os.Parcel.readException(Parcel.java:2005)
                      at android.os.Parcel.readException(Parcel.java:1951)
                      at com.android.internal.telecom.ITelecomService$Stub$Proxy.registerPhoneAccount(ITelecomService.java:1019)
                      at android.telecom.TelecomManager.registerPhoneAccount(TelecomManager.java:972)
                      at com.dmarc.cordovacall.CordovaCall.initialize(CordovaCall.java:71)
                      at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                      at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
                      at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
                      at org.apache.cordova.PluginManager.init(PluginManager.java:86)
                      at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
                      at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
                      at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
                      at com.komedhealth.frontend.MainActivity.onCreate(MainActivity.java:39)
                      at android.app.Activity.performCreate(Activity.java:7009)
                      at android.app.Activity.performCreate(Activity.java:7000)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6494) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by Zymr-Gunjan** [comment]
Getting same issue, is there any update on this to how resolve it?
