### ISSUE TITLE
NoClassDefFoundError: android.telecom.PhoneAccountHandle

### ISSUE THREAD

**Issue by utiq** [WebsiteBeaver/CordovaCall#63]
I get this error when I try to run my app in an emulator.

cordova: 8.1.2 (cordova-lib@8.1.1)
CordovaCall: 1.1.6

```
W/dalvikvm( 2452): threadid=1: thread exiting with uncaught exception (group=0x9cd7bb20)
E/AndroidRuntime( 2452): FATAL EXCEPTION: main
E/AndroidRuntime( 2452): Process: io.solidpixels.napsergeant, PID: 2452
E/AndroidRuntime( 2452): java.lang.NoClassDefFoundError: android.telecom.PhoneAccountHandle
E/AndroidRuntime( 2452): 	at com.dmarc.cordovacall.CordovaCall.initialize(CordovaCall.java:65)
E/AndroidRuntime( 2452): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
E/AndroidRuntime( 2452): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
E/AndroidRuntime( 2452): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
E/AndroidRuntime( 2452): 	at org.apache.cordova.PluginManager.init(PluginManager.java:86)
E/AndroidRuntime( 2452): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
E/AndroidRuntime( 2452): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
E/AndroidRuntime( 2452): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
E/AndroidRuntime( 2452): 	at io.solidpixels.napsergeant.MainActivity.onCreate(MainActivity.java:39)
E/AndroidRuntime( 2452): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 2452): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 2452): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
E/AndroidRuntime( 2452): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/AndroidRuntime( 2452): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 2452): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 2452): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2452): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2452): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 2452): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2452): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2452): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2452): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2452): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1604):   Force finishing activity io.solidpixels.napsergeant/.MainActivity
```
I created this emulator:

<img width="610" alt="screen shot 2018-11-20 at 5 02 18 pm" src="https://user-images.githubusercontent.com/1144196/48812203-227c3a00-ece6-11e8-848a-7760e5e4d85d.png">

Emulator details):

```
Name: Nexus_5X
CPU/ABI: Intel Atom (x86)
Path: /Users/cesar/.android/avd/Nexus_5X.avd
Target: default [] (API level 19)
Skin: nexus_5x
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5X
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 19
tag.id: default
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Nexus 5X
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1920
vm.heapSize: 228
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-19/default/x86/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Nexus_5X
hw.lcd.density: 420
hw.arc: false
hw.device.hash2: MD5:bc5032b2a871da511332401af3ac6bb0
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: 
runtime.network.latency: none
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

**Comment by sido420** [comment]
I am hitting the same issue on Play store test on Samsung S3 

@utiq Did you find a solution for this issue?

**Comment by danielehrhardt** [comment]
Same Issue here
